Algoritmo "media"
Var a, b : inteiro

Inicio
   escreva("Informe o primeiro valor: ")
   leia(a)
   escreva("Informe o segundo valor: ")
   leia(b)

   Se (a = b) entao
      escreval ("Os valores são iguais")

   senao
      se(a > b) entao
         escreval ("O 1º valor é maior, ele é o: ", a)

      senao
         escreval("O 2º valor é maior, ele é o: ", b)
      Fimse
   Fimse

Fimalgoritmo